### ISSUE TITLE
q2

### ISSUE THREAD

**Issue by suuuuubin** [suuuuubin/sseungsu#2]
1321q32

**Comment by ss4483** [comment]
5456

**Comment by suuuuubin** [comment]
hgfhgf

**Comment by ss4483** [comment]
ㅓㅘㅕㅗ

**Comment by ss4483** [comment]
시작햇어?

**Comment by ss4483** [comment]
?????

**Comment by suuuuubin** [comment]
zzzz

**Comment by suuuuubin** [comment]
형메일주소점여

**Comment by ss4483** [comment]
ss4483@naver.com

**Comment by suuuuubin** [comment]
d여기 파일업로드못하는가여

**Comment by ss4483** [comment]
그런거같은데 ?

**Comment by suuuuubin** [comment]
아니면 형 제 c9조ㅗㅁ 와주세요

**Comment by ss4483** [comment]
들옴

**Comment by suuuuubin** [comment]
왼쪽에 docx 가 문젠데 4번만하면돼요

**Comment by ss4483** [comment]
docx가 깨져보이는데

**Comment by suuuuubin** [comment]
세ㅐ로올렷어요

**Comment by ss4483** [comment]
어ㅏ문제열엇다

**Comment by ss4483** [comment]
지금 어디에서 풀고잇누ㅡㄴ거야 ?

**Comment by ss4483** [comment]
뭐도와주면되 이거문제에서 ??

**Comment by suuuuubin** [comment]
4q번만하면끝

**Comment by suuuuubin** [comment]
4번손도 못대겠는데유

**Comment by ss4483** [comment]
<h2 id="first-title"> First Title </h1>
    <p id="first-body"> First Body <p>
    <h2 id="second-title"> Second Title </h1>
    <p id="second-body"> Second Body <p>
    <h2 id="third-title"> Third Title </h1>
    <p id="third-title"> Third Body <p>
    <h2 id="forth-title"></h2> Forth Title </h1>
    <p id="forth-title"> Forth Body <p>
    <h2 id="fifth-title"></h2> Fifth Title </h1>
    <p id="fifth-title"> Fifth Body <p>
이렇게 id값주고 시작해도되지 ?

**Comment by suuuuubin** [comment]
네 아무렇게나해서 성공마낳면돼여

**Comment by suuuuubin** [comment]
형 다하시면 4.html에 해주세요

**Comment by ss4483** [comment]
4.html 에 일단 버튼클릭하면 값가져오는건 다됐는데 저걸로 각가 하면될거같은데

**Comment by ss4483** [comment]
생각나는게 if문뿐인데 너무길어지네 ./. 이거 4시까지야 ?;;

**Comment by suuuuubin** [comment]
네..

**Comment by suuuuubin** [comment]
if한두개만 해주시면 같이해용

**Comment by ss4483** [comment]
너무노가단데이거 ...

**Comment by ss4483** [comment]
아ㅣ거 odd랑 even 홀수 짝수번째꺼 다바뀐느거지 ?

**Comment by ss4483** [comment]
color는 다하긴햇는데

**Comment by ss4483** [comment]
수정은 다된거같거든

**Comment by ss4483** [comment]
아수정다시햇다 잘못댄거잇어서

**Comment by suuuuubin** [comment]
ㅋㅋ 형 이거 대충하고 내야할거같아요 지금 근데 안바뀌는뎅

**Comment by ss4483** [comment]
다시하믄댈건데 
수정은 다대던데
